/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/data/chart': RouteRecordInfo<'/data/chart', '/data/chart', Record<never, never>, Record<never, never>>,
    '/data/search': RouteRecordInfo<'/data/search', '/data/search', Record<never, never>, Record<never, never>>,
    '/game/lobby': RouteRecordInfo<'/game/lobby', '/game/lobby', Record<never, never>, Record<never, never>>,
    '/help/about': RouteRecordInfo<'/help/about', '/help/about', Record<never, never>, Record<never, never>>,
    '/help/help': RouteRecordInfo<'/help/help', '/help/help', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/data/chart.vue': {
      routes: '/data/chart'
      views: never
    }
    'src/pages/data/search.vue': {
      routes: '/data/search'
      views: never
    }
    'src/pages/game/lobby.vue': {
      routes: '/game/lobby'
      views: never
    }
    'src/pages/help/about.vue': {
      routes: '/help/about'
      views: never
    }
    'src/pages/help/help.vue': {
      routes: '/help/help'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
